language: python

before_install:
  - pip install hererocks
  - hererocks env --luajit 2.0.3 --luarocks latest
  - source env/bin/activate

install:
  - luarocks install luacheck

script:
  - git ls-files | grep -f .grep | xargs --no-run-if-empty luacheck --std min+garrysmod+spacebuild
